version: '3.7'
services:
  registry:
    build: .
    container_name: registry
    restart: unless-stopped
    ports:
      - 9922:3000
    environment:
      - MENSA_ENDPOINT
      - WETTER_ENDPOINT
      - OEFFNUNGSZEITEN_ENDPOINT
      - DATABASE_ENDPOINT
      - CATS_ENDPOINT
      - STT_ENDPOINT
      - TTS_ENDPOINT
      
networks:
  default:
    external:
      name: beuthbot_network
