# https://docs.docker.com/compose/compose-file/
version: "2.0"

services:
  registry-microservice:
    container_name: registry-microservice
    privileged: true
    build:
      context: ./
    restart: always
    networks:
      - web
    expose:
      - 3000
    volumes:
      - .:/app

networks:
  web:
    external: true