version: '3.7'
services:
  registry:
    build: .
    restart: unless-stopped
    ports:
      - 9922:3000
    environment:
      - MENSA_ENDPOINT
      - WETTER_ENDPOINT
      - OEFFNUNGSZEITEN_ENDPOINT
networks:
  default:
    external:
      name: beuthbot_network